# Generated by Django 5.0.4 on 2024-05-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', '뉴스'), ('ask', 'Ask'), ('show', 'Show')], default='news', max_length=10),
        ),
    ]
