# Generated by Django 4.2 on 2024-05-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_content_article_created_at_article_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
